name: example
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  faker: ^2.2.0
  flutter:
    sdk: flutter
  teil_forms:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  teil_lints:
    hosted: https://volltech.jfrog.io/artifactory/api/pub/pub
    version: ^0.0.5+3

flutter:
  uses-material-design: true
