name: example
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  faker: ^2.2.0
  flutter:
    sdk: flutter
  go_router: ^14.5.0
  json_annotation: ^4.9.0
  teil_forms:
    path: ../

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
