include: ../../analysis_options.yaml

linter:
  rules:
    # TODO(Ohashi): Remove this rule when all public members have documentation.
    public_member_api_docs: false

analyzer:
  language:
    strict-raw-types: false
