name: teil_forms
description: "A new Flutter package project."
version: 0.0.2
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  teil_lints:
    hosted: https://volltech.jfrog.io/artifactory/api/pub/pub
    version: ^0.0.5+3
