name: teil_tools

repository: https://github.com/voll-labs/teil_tools

packages:
  - packages/**

command:
  version:
    branch: main
    linkToCommits: true
    workspaceChangelog: true
    releaseUrl: true

scripts:
  analyze:
    description: Analyze Dart code.
    run: |
      melos exec -c 10 -- \
        flutter analyze --fatal-infos

  test:
    description: Run Flutter tests in this project.
    run: melos exec -- flutter test
    packageFilters:
      dirExists:
        - test

  coverage:
    description: Generate coverage for the selected package.
    run: |
      melos exec -- flutter test --coverage &&
      melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
    packageFilters:
      dirExists: test
