name: teil_lints
description: A new Flutter package project.
version: 0.0.2
repository: https://github.com/voll-labs/teil_tools

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_code_metrics: ^5.7.0
  dart_code_metrics_presets: ^1.5.0
  very_good_analysis: ^4.0.0+1
