name: Analyze main

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - uses: bluefireteam/melos-action@v3
      - name: Run test coverage
        run: melos run coverage
