name: Publish release

on:
  push:
    tags:
      - teil_tools-v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - uses: bluefireteam/melos-action@main
      - name: Publish release
        run: melos publish --no-dry-run --yes
